#!/bin/bash
# Note: I chose to remove the tiff file, for personal preferences

name=$(zenity --entry --text="Name of file?")
# scanimage can also be set to scan as .jpeg personal preference should prevail
scanimage > $name.tiff --mode color --resolution 300
# This could easily be done with convert, but for filesizes
#libreoffice --convert-to pdf $name.tiff
convert $name.tiff -resize x1024 $name.pdf
#to prevent the script removing the file, comment out this line.
rm ./$name.tiff
