#!/bin/bash
# Requires Thunderbird

path=$(dirname "$(readlink -f "$1")")
list="$path/"$(basename "$(readlink -f "$1")")
shift
for i in $@ ; do
path=$(dirname "$(readlink -f "$i")")
list=$list",$path/"$(basename "$(readlink -f "$i")")
done
thunderbird -compose "attachment='$list'"
